version: '2'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: yep_clock
  grails:
    build: .
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: yep_clock
      DB_PORT: 5432
      DB_NAME: postgres
